# Generated by Django 4.2.2 on 2025-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='enddate',
            field=models.DateField(default=None),
        ),
    ]
