# Generated by Django 4.2.2 on 2025-06-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_exam_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assement',
            name='que',
        ),
    ]
