# Generated by Django 4.2.2 on 2025-06-14 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_assement_que'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('scored', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.exam')),
            ],
        ),
    ]
