# Generated by Django 4.2.2 on 2025-06-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_assementanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assement',
            name='is_attemp',
            field=models.BooleanField(default=False),
        ),
    ]
